server:
  port: 9090
  servlet:
    context-path: '/api/v*'
  jetty:
    threads:
      max: 300


logging:
  level:
    org.hibernate.sql: trace

spring:
  application:
    name: debezium-demos
  main:
    lazy-initialization: true # For fast start up need to check the metrics as well.
  datasource:
    url: jdbc:postgresql://[::1]:5433/app_db # IPv6 connection to postgresql server.
    username: app_user
    password: app_pass_123
    hikari:
      maximum-pool-size: 50
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        cache:
          use_query_cache: false
          use_second_level_cache: false
        connection:
          pool_size: 50
        jdbc:
          batch_size: 50
          fetch_size: 50


