--create PRODUCTS
CREATE TABLE PRODUCTS(
    PRODUCT_ID UUID PRIMARY KEY UNIQUE NOT NULL ,
    NAME VARCHAR NOT NULL ,
    STOCK_CODE VARCHAR NOT NULL UNIQUE ,
    PRICE NUMERIC(18, 2) NOT NULL
Yeah);